# Generated by Django 4.1.2 on 2022-10-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_country_genre_author_birthday_author_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
