# Generated by Django 4.1.2 on 2022-11-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_author_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
